[package]
name = "music-assistant-companion"
version = "0.0.47"
description = "Music Assistant Companion App"
authors = ["The Music Assistant Team"]
license = "Apache-2.0"
repository = "https://github.com/music-assistant/companion"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = [ "devtools", "tray-icon"] }
tauri-plugin-single-instance = "2.0.0-beta"
tauri-plugin-window-state = "2.0.0-beta"
discord-rich-presence = "0.2.4"
tungstenite = {version = "0.21.0", features = ["native-tls"] }
url = "2.5.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
gethostname = "0.4.3"
tauri-plugin-shell = "2.0.0-beta.6"
tauri-plugin-process = "2.0.0-beta.5"

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-updater = "2.0.0-beta.6"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib", "lib"]
